### PR TITLE
Added PartialPooling example to demo repo

### PR DESCRIPTION
**Pull request by stablemarkets**
Hi, 

I've been writing up an example demonstrating partial pooling using Nimble. I thought it could make a good addition to your set of examples. In particular, going through how to choose specific samplers and monitoring transformations of posterior draws.

Best,
Arman

### CODE REVIEW

**Comment by danielturek** [comment]
@stablemarkets We are hugely appreciative of this example submission.  Thanks for putting this together.

Can I make a small number of suggestions for minor changes?

- Per the standard syntax of the `nimble-demos` repository, perhaps changing the folder name to `partial_pooling` ?
- At least in the version I'm seeing, it seems one latex equation is mis-formed and not rendering.  It's early in the section titled "Bayesian Analysis Using Nimble", just following the centered logit(p_i) equation, and (unrendered) appears as: `$_j N(0,sd=2) $`
- Your code for the `addSampler` method could change a little.  In particular, the control list element `targetNodes = 'beta'` is a relic of old MCMC configuration syntax.  That's no longer used at all, and can be removed.  The target node is completely determined by the argument `target = 'beta'`.  Also, the control list element `adaptive = TRUE` is the default for the `RW_block` sampler.  So if you're including it only to highlight that the sampler is adaptive, then fine.  But if you leave that out, it will function exactly the same.  So, your `addSampler` code could be reduced to:
```
spec$addSampler(type = 'RW_block', target ='beta')
```
- In addition, I would rather you not suggest that people directly access/edit fields of the `spec` object using `$`, since the underlying structure of the `spec` object could change (in this case, when you change the monitors using `spec$monitors <- c('p_comp')`).  Rather, this should be done using the methods provided with the `spec` object, and be replaced by:
```
spec$resetMonitors()
spec$addMonitors('p_comp')
```
- Again, when you run the MCMC, it looks like you're using a little older NIMBLE syntax:
```
compiled_mcmc$run(10000)
samples <- as.matrix(compiled_mcmc$mvSamples)
summary(samples)
```
I would suggest replacing these lines by the newer function:
```
out <- runMCMC(compiled_mcmc, 10000, summary = TRUE)
```

The `runMCMC` method provides a lot of other user-friendly options, such as `thin`, `nchains`, `inits`, `nburnin`, `summary`, `WAIC`, and probably others, too.  See `help(runMCMC)`.

You might also add the reference at the end:

> Perry de Valpine, Daniel Turek, Christopher Paciorek, Clifford Anderson-Bergman, Duncan Temple Lang and Rastislav Bodik (2017).  Programming with models: writing statistical algorithms for general model structures with NIMBLE.  \textit{Journal of Computational and Graphical Statistics}, 26(2): 403-413.

Once this demo is finished and live, I hope you share it with other researchers in your field.

Cheers!

**Comment by stablemarkets** [comment]
Thanks for the helpful suggestions, @danielturek! I implemented them and made another commit. Let me know if you have other suggestions. 

The LaTeX for the prior was rendering fine on my end. Let me know if it's still off for you.

Also I renamed the folder to partial_pooling, but for some reason the old PartialPooling folder is still showing up on GitHub even though it's not in my cloned local repository on my desktop. Not sure how to delete it.

I plan on sharing it on Twitter once it's live!

**Comment by danielturek** [comment]
@stablemarkets I haven't taken a look at your changes yet, but regarding the persistent files / folder, I usually have to:

```
git rm --cached PartialPooling/XXX
git rm --cached PartialPooling
```
where you'll also have to fill in the specific file names in place of `XXX` (cannot use wildcard matching using `*`), since as the files no longer exist, bash wildcard expansion won't find them.  Then do another commit.

But there's also a chance I'm totally off, and misunderstanding the problem.

**Comment by stablemarkets** [comment]
Thanks! Looks like your suggestion worked. The folder is no longer there.

**Comment by danielturek** [comment]
@stablemarkets Changes look great.  Thank you again for the submission.

**Comment by perrydv** [comment]
Thanks for the demo @stablemarkets and for the code review @danielturek.  The only tiny apparent typo I noticed is in the latex equation for `logit(p_i)`, where there are two terms with `C_i`.  Should the second one use `D_i`?

Nice use of block sampling for this example. 

BTW, whereas "C++ back-end" often refers to use of a static C++ library, NIMBLE is code-generating C++ for each model and set of algorithms.

One of us can merge after you reply about `C_i` vs. `D_i`.  Thanks again!

**Comment by danielturek** [comment]
@stablemarkets @perrydv I'll let the rest of this to either of you, since I'm away from a proper computer for the next week or so.

**Comment by stablemarkets** [comment]
Thanks @perrydv! Good catch with the extra C_i. I just pushed a commit with the change.

**Comment by perrydv** [comment]
👍

**Pull request merged**
