### PR TITLE
removed prior calc when determining reduced model logProb

### PR DESCRIPTION
**Pull request by paciorek**
WAIT TO MERGE until discussion below and until I regenerate the html.

@perrydv did you just manually create the reversible_jump.html and png files or is there a script/Makefile hidden somewhere to do this? 

Also I didn't (yet?) update nimble_reversible_jump.{Rhtml,html} as I wasn't sure how this fit into things.

### CODE REVIEW

**Comment by paciorek** [comment]
Also I wonder if we should make a comment about use of posterior model probs, p(model | data) (as RJMCMC implicitly does) being sensitive to vague priors. In this example changing p(b2) from N(0,sd=100) to N(0,sd=10) changes Pr(b2=0 | data) from 0.97 to 0.75.  Sensitivity is not the point of the example, but may be a reason for folks to be cautious about taking this sort of approach to model selection.

**Comment by perrydv** [comment]
1. Oh, sorry those files are a bit confusing.  `nimble_reversible_jump.Rhtml` is the source code for the blog post.  `knitr` converts it to `nimble_reversible_jump.html`.  Doing it from `Rhtml` source makes it easier to post via wordpress.  

2.  `reversible_jump.[rmd, html]` are the source and output on the examples page.  I think I intended to replace that with the blog post content but that didn't happen.  So I suggest working from `nimble_reversible_jump` and discarding `reversible_jump`.

3. Up to you on commenting about the statistical challenges as opposed to the implementation available via nimble.

**Comment by perrydv** [comment]
Otherwise, 👍

**Comment by paciorek** [comment]
Ok, I'm updating nimble_reversible_jump.Rhtml and removing reversible_jump*.

Do you create the html with
```
knit2html('nimble_reversible_jump.Rhtml')
```
The output that is produced for me doesn't look as nice as your original nimble_reversible_jump.html and the file is somewhat bigger.

**Comment by paciorek** [comment]
Ok, nimble_reversible_jump.Rhtml is all set. It looks like the reversible_jump.html currently used in the r-nimble.org example may have been generated by pandoc and I'm not sure how to replicate that process (in order for format of revised RJ example to match the other examples) so this will have to wait for @perrydv to fill me in.

**Comment by perrydv** [comment]
@paciorek I believe all I did to build `nimble_reversible_jump.html` is `library(knitr); knit('nimble_reversible_jump.Rhtml')`.  I don't think I did anything manually with `pandoc`.  I just pushed an updated version of your `rj_remove_prior` branch after re-running `knit('nimble_reversible_jump.Rhtml')`.  Please go ahead and add a `makefile` or a comment in the `Rhtml` file explaining how to build it in the future.

I think you said you would remove `reversible_jump.*` but those files still seem to be there on the branch.

**Comment by paciorek** [comment]
ok, so there's still some confusion here; let me try to lay things out more specifically. 

nimble_reversible_jump.Rhtml was the source of the blog post.

reversible_jump.rmd was the source of the r-nimble.org demo. 

So to try to match the r-nimble.org demo formatting the easiest thing for me to do is simply work with the reversible_jump.rmd file because I don't know how to pass the Rhtml file through knitr and get output that looks anything like the r-nimble.org demo. I used knit2html on reversible_jump.rmd and put the resulting reversible_jump.html up on r-nimble.org (I now link to the reversible_jump.html that is in `nature.berkeley.edu:/web/R-nimble/wordpress/nimbleExamples`). However, the formatting of the reversible jump example is now somewhat different than the other examples - e.g., the section headers are `<h3>` and not `<h1>`. I'm not sure what additional steps @perrydv  took when generating each examples html file to make them have the formatting that they do.  

@perrydv We've gone back and forth on this enough that it's probably worth a 5 minute Skype chat if you have a chance so we can try to iron things out directly. Or if you want to just look at the current reversible jump formatting on r-nimble.org and you see what is different, feel free to fix yourself if you see what the issue is.

**Comment by paciorek** [comment]
Ok, the html linked to from the examples page is updated to match formatting of other examples and the example now lives in the r-nimble area of nature.b.e.

next steps are to move all html example files from Perry's nature.b.e domain into the nimble area

also @perrydv I'll let you decide about adding a comment to the blog post pointing out the bug and referring to the example for revised code.

**Pull request merged**
